name: d8multi
recipe: drupal10
config:
  php: '8.2'
  webroot: docroot
proxy:
  adminer:
    - adminer.d8multi.lndo.site
  appserver:
    - sentinel.lndo.site
    - pd.lndo.site
  mailhog:
    - mail.d8multi.lndo.site
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/docroot'
  database: disabled
  pd:
    type: mariadb:10.11
    creds:
      user: database
      password: database
      database: database
    portforward: 33069
  sentinel:
    type: mariadb:10.11
    creds:
      user: database
      password: database
      database: database
    portforward: 33070
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: '/bin/s6-svscan /etc/services.d'
    portforward: true
  node:
    type: 'node:14'
    overrides:
      ports:
        - '3051:3051'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
tooling:
  composer:
    service: appserver
    cmd: '/usr/local/bin/composer'
  npm:
    service: node
  yarn:
    service: node
  node:
    service: node
  gulp:
    service: node
  backstop:
    service: node
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
