popup_agreed:
  value: '<h2>Merci d''avoir accepté les cookies</h2><p>Vous pouvez désormais masquer ce message ou en apprendre plus à propos des cookies.</p>'
popup_agree_button_message: 'Oui, je suis d''accord'
popup_disagree_button_message: 'En savoir plus'
popup_find_more_button_message: 'En savoir plus'
popup_hide_button_message: Masquer
popup_info:
  value: '<span>Nous utilisons des cookies pour améliorer ce site. Cliquer sur un lien sur ce site est considéré comme un accord implicite à cela.</span>'
popup_link: /fr/politique-de-confidentialite
disagree_button_label: 'Non, merci.'
withdraw_action_button_label: 'Retirer le consentement'
withdraw_tab_button_label: 'Paramètres de confidentialité'
