display:
  block_1:
    display_title: 'Revues de presse'
    display_options:
      block_description: 'Revues de presse'
      title: 'Revues de presse'
  block_2:
    display_title: 'Emissions radio'
    display_options:
      block_description: 'Emissions radio'
      title: 'Emissions radio'
