display:
  page_1:
    display_options:
      fields:
        field_image:
          alter:
            text: "<div class=\"field--type-image\">{{ field_image }}\r\n<div class=\"ctype\">{{ type }} </div>\r\n</div>"
        nothing:
          alter:
            text: "{{ field_image }}\r\n<h4 class=\"node--title>{{ title }}</h4>\r\n<span class=\"date\">{{ field_date }}</span>"
      header:
        area:
          content:
            value: "<h3>Dernières actualités&nbsp;&nbsp;<a href=\"/fr/actualites\"><button class=\"btn btn-outline-secondary\">Tout voir</button></a></h3>\r\n"
            format: full_html
    display_title: Page
  block_1:
    display_options:
      header:
        area:
          content:
            value: "<h3>Dernières publications&nbsp;&nbsp;<a href=\"/fr/publications\"><button class=\"btn btn-outline-secondary\">Tout voir</button></a></h3>\r\n"
            format: full_html
      title: 'Dernières publications'
    display_title: 'Dernières ressources'
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
    display_title: Maître
  feed_1:
    display_title: Flux
label: 'Page d''accueil'
description: 'Tout le contenu promu en page d''accueil.'
