display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Rechercher
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      filters:
        search_api_fulltext:
          expose:
            label: 'Parcourir nos publications'
            placeholder: 'Termes de recherche'
      sorts:
        field_pubdate:
          admin_label: Tris
        title:
          expose:
            label: Titre
        search_api_relevance:
          expose:
            label: Pertinence
      title: Publications
      empty:
        result:
          content: '<h3>Votre recherche n''a aucun résultat.</h3>'
label: Publications
