site_key: 6LcPEpoUAAAAAIRhDSYeVI-AIiT5liObtH0hVBu-
secret_key: 6LcPEpoUAAAAAOGSZn4hr2rN-sUByhz8tmBoZs-U
verify_hostname: false
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: true
_core:
  default_config_hash: eKR4FfUD7Cp3bXamsCz6GAxh0PCLIZNMa65y2kChIh0
