id: caption
label: Caption
ui_limit: ''
type: token
type_label: 'Token field'
entities:
  node: node
properties:
  content:
    value: "<span>[node:field_image:0:title]</span>\r\n"
    format: full_html
