api_key: f47ceb2ef23c15a1da6d3e17d53d13f1-us20
cron: false
batch_limit: 500
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
enable_connected: true
connected_id: ea9b0635f6ffecf
connected_paths: ''
