_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
api_key: 2804c1f6f24d8dab810c8de2995dc55f-us20
oauth_middleware_url: 'https://drupal-mailchimp-oauth.uw.r.appspot.com'
api_timeout: 10
cron: false
batch_limit: 500
api_classname: Mailchimp\Mailchimp
test_mode: false
enable_connected: true
connected_id: null
connected_paths: null
webhook_hash: 9b10204187a96adabf3bc5d516f4be8f
optin_check_email_msg: 'Please check your email to confirm your subscription.'
