_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
api_key: 81fa0f1217a168891b9dc8c1153a0f14-us20
api_timeout: 10
cron: false
batch_limit: 500
api_classname: Mailchimp\Mailchimp
test_mode: false
enable_connected: true
connected_id: null
connected_paths: null
webhook_hash: 9b10204187a96adabf3bc5d516f4be8f
