_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  better_passwords: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  clamav: 0
  colorbox: 0
  components: 0
  config: 0
  config_split: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_usage: 0
  facets: 0
  field: 0
  field_layout: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  google_tag: 0
  honeypot: 0
  http_response_headers: 0
  image: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  klaro: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_entity_browser: 0
  media_library: 0
  menu_link_attributes: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  password_policy_character_types: 0
  password_policy_history: 0
  password_policy_length: 0
  password_policy_username: 0
  path: 0
  path_alias: 0
  pdfpreview: 0
  phpass: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  recaptcha: 0
  search: 0
  search_api: 0
  search_api_db: 0
  seckit: 0
  session_limit: 0
  sophron: 0
  svg_image: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  username_enumeration_prevention: 0
  varnish_purge_tags: 0
  varnish_purger: 0
  webform: 0
  webform_ui: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  ds_extras: 2
  password_policy: 10
  views: 10
  paragraphs: 11
  password_policy_extras: 20
  minimal: 1000
  readonlymode: 9999
theme:
  stark: 0
  bootstrap_barrio: 0
  sentinel_bootstrap_sass: 0
  claro: 0
profile: minimal
